spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/f1betting
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  docker:
    compose:
      enabled: true

f1-external-api:
  active-provider: openf1
  providers:
    openf1:
      url: https://api.openf1.org
    ergast:
      url: https://ergast.com/api/f1
